version: "3.8"
services:
  jupyterlab:
    container_name: "${DIR}-jupyterlab-cuda"
    user: ${UID}:${GID}
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        UID: ${UID}
        GID: ${GID}
        UNAME: ${UNAME}
        GNAME: ${GNAME}
    shm_size: "2gb"
    restart: always
    tty: true
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/workspace
    working_dir: "/workspace"
    command: jupyter-lab --ip 0.0.0.0 --port=8080 --allow-root --no-browser --NotebookApp.token=""

  streamlit:
    container_name: "${DIR}-streamlit-cuda"
    user: ${UID}:${GID}
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        UID: ${UID}
        GID: ${GID}
        UNAME: ${UNAME}
        GNAME: ${GNAME}
    shm_size: "2gb"
    restart: always
    tty: true
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    ports:
      - "8501:8501"
    volumes:
      - ./workspace:/workspace
    working_dir: "/workspace"
    command: streamlit run app.py
